spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/walkman/SpringcloudConfig
          searchPaths: respo
          username:
          password:

server:
  port: 8888
